# Generated by Django 5.2.6 on 2026-08-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='factory/videos/'),
        ),
        migrations.AlterField(
            model_name='factoryvideo',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
