# Generated by Django 5.2.6 on 2026-08-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_factoryvideo_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Cover thumbnail image for the video player', null=True, upload_to='factory/videos/thumbnails/'),
        ),
    ]
