# Generated by Django 5.2.6 on 2026-08-25 15:30

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_factoryvideo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryvideo',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Cover thumbnail image for the video player', null=True, upload_to='factory/videos/thumbnails/'),
        ),
    ]
