# Generated by Django 5.2.6 on 2026-08-26 14:42

import factory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_alter_factoryvideo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=factory.models._get_video_storage, upload_to='factory/videos/'),
        ),
    ]
