# Generated by Django 5.2.6 on 2026-08-21 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModelSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='OEM & ODM Solutions', max_length=200)),
                ('subtitle', models.TextField(default='Whether you have your own unique product design or want to leverage our existing high-quality manufacturing lines under your own brand, we offer flexible models to suit your business needs.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessModelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to hide/show this section on the frontend.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of this section on the page (lower numbers appear first).')),
                ('title', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('quote', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='briefcase', max_length=50)),
                ('features', models.TextField(blank=True, help_text='Format: Key: Value, one per line. E.g. Design: Yours')),
                ('color_theme', models.CharField(choices=[('blue', 'Blue'), ('magenta', 'Magenta')], default='blue', max_length=50)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.businessmodelsection')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
