# Generated by Django 5.2.6 on 2026-08-05 18:04

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to hide/show this section on the frontend.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of this section on the page (lower numbers appear first).')),
                ('title', models.CharField(max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='certificates/gallery/')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CertificatesCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Need Details About Our Standards?', max_length=200)),
                ('description', models.TextField()),
                ('btn1_text', models.CharField(default='Request Documents', max_length=50)),
                ('btn1_link', models.CharField(default='/contact/', max_length=200)),
                ('btn2_text', models.CharField(default='Back to Services', max_length=50)),
                ('btn2_link', models.CharField(default='/services/', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CertificatesHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Certified Excellence', max_length=200)),
                ('subtitle', models.TextField()),
                ('bg_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='certificates/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
