# Generated by Django 5.2.6 on 2026-08-05 18:04

import ckeditor.fields
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Optimal length is 50-60 characters.', max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='Optimal length is 150-160 characters.', verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255, verbose_name='Meta Keywords')),
                ('canonical_url', models.URLField(blank=True, help_text='Leave blank to use the current page URL.', verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, help_text='Title for Facebook/LinkedIn sharing.', max_length=255, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='Description for Facebook/LinkedIn sharing.', verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, help_text='Image for Facebook/LinkedIn sharing (1200x630px recommended).', null=True, upload_to='seo/og/', verbose_name='OG Image')),
                ('robots_index', models.BooleanField(default=True, help_text='Allow search engines to index this page.', verbose_name='Index')),
                ('robots_follow', models.BooleanField(default=True, help_text='Allow search engines to follow links on this page.', verbose_name='Follow')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to hide/show this section on the frontend.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of this section on the page (lower numbers appear first).')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Optimal length is 50-60 characters.', max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='Optimal length is 150-160 characters.', verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255, verbose_name='Meta Keywords')),
                ('canonical_url', models.URLField(blank=True, help_text='Leave blank to use the current page URL.', verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, help_text='Title for Facebook/LinkedIn sharing.', max_length=255, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='Description for Facebook/LinkedIn sharing.', verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, help_text='Image for Facebook/LinkedIn sharing (1200x630px recommended).', null=True, upload_to='seo/og/', verbose_name='OG Image')),
                ('robots_index', models.BooleanField(default=True, help_text='Allow search engines to index this page.', verbose_name='Index')),
                ('robots_follow', models.BooleanField(default=True, help_text='Allow search engines to follow links on this page.', verbose_name='Follow')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to hide/show this section on the frontend.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of this section on the page (lower numbers appear first).')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('featured_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blog/')),
                ('published_date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
