# Generated by Django 5.2.6 on 2026-08-05 18:04

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='State-of-the-art Production Facilities', max_length=200)),
                ('description', models.TextField()),
                ('img_top_left', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='home/factory/')),
                ('img_top_right', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='home/factory/')),
                ('img_bottom_left', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='home/factory/')),
                ('box_percentage', models.CharField(default='100%', max_length=10)),
                ('box_text', models.CharField(default='Quality Inspected Before Shipping', max_length=100)),
            ],
            options={
                'verbose_name': 'Home Factory Section',
                'verbose_name_plural': 'Home Factory Section',
            },
        ),
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_black', models.CharField(default='Uncompromising', max_length=100)),
                ('title_magenta', models.CharField(default='Quality.', max_length=100)),
                ('title_gold', models.CharField(default='Protect.', max_length=100)),
                ('title_prefix', models.CharField(default='Engineered to', max_length=100)),
                ('subtitle', models.TextField(default='Direct from our 50,000 sqm production facility...')),
                ('badge_text', models.CharField(default='Global Source Manufacturer', max_length=50)),
                ('primary_cta_text', models.CharField(default='Explore Products', max_length=50)),
                ('primary_cta_link', models.CharField(default='#products', max_length=200)),
                ('secondary_cta_text', models.CharField(default='Request a Quote', max_length=50)),
                ('secondary_cta_link', models.CharField(default='/contact/', max_length=200)),
            ],
            options={
                'verbose_name': 'Home Hero Section',
                'verbose_name_plural': 'Home Hero Section',
            },
        ),
        migrations.CreateModel(
            name='HomeMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Forging the strongest connections worldwide.', max_length=200)),
                ('description', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='home/mission/')),
                ('stat1_number', models.CharField(default='20+', max_length=20)),
                ('stat1_text', models.CharField(default='Years Experience', max_length=50)),
                ('stat2_number', models.CharField(default='50+', max_length=20)),
                ('stat2_text', models.CharField(default='Countries Served', max_length=50)),
                ('stat3_number', models.CharField(default='100%', max_length=20)),
                ('stat3_text', models.CharField(default='Quality Assured', max_length=50)),
            ],
            options={
                'verbose_name': 'Home Mission Section',
                'verbose_name_plural': 'Home Mission Section',
            },
        ),
        migrations.CreateModel(
            name='HomeValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Core Values', max_length=200)),
                ('description', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='home/values/')),
            ],
            options={
                'verbose_name': 'Home Values Section',
                'verbose_name_plural': 'Home Values Section',
            },
        ),
        migrations.CreateModel(
            name='HomeFactoryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to hide/show this section on the frontend.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of this section on the page (lower numbers appear first).')),
                ('icon', models.CharField(default='factory', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='home.homefactory')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to hide/show this section on the frontend.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of this section on the page (lower numbers appear first).')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='home/hero/')),
                ('alt_text', models.CharField(default='Hero Slide', max_length=100)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='home.homehero')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeValueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to hide/show this section on the frontend.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of this section on the page (lower numbers appear first).')),
                ('icon', models.CharField(default='shield', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('values_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.homevalues')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
