# Generated by Django 5.2.6 on 2026-08-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='photo',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(default='Default Company', max_length=255, verbose_name='Company Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(default='Default Contact', max_length=255, verbose_name='Contact Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Customer ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Prospect', 'Prospect'), ('Customer', 'Customer'), ('Partner', 'Partner')], default='Lead', max_length=50, verbose_name='Customer Type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_contact_date',
            field=models.DateField(blank=True, null=True, verbose_name='First Contact Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_contact_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Contact Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='lead_source',
            field=models.CharField(choices=[('Website', 'Website'), ('Referral', 'Referral'), ('Cold Reachout', 'Cold Reachout'), ('LinkedIn', 'LinkedIn'), ('Exhibition', 'Exhibition'), ('Other', 'Other')], default='Website', max_length=50, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='customer',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='customer',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next Follow-up Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='customer',
            name='position',
            field=models.CharField(blank=True, max_length=150, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='customer',
            name='product_interest',
            field=models.TextField(blank=True, verbose_name='Product Interest'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending'), ('Hot', 'Hot (Highly Interested)'), ('Warm', 'Warm'), ('Cold', 'Cold')], default='Active', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, verbose_name='WhatsApp'),
        ),
    ]
