# Generated by Django 5.2.6 on 2026-08-05 18:04

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutExcellence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Engineering Excellence at Scale', max_length=200)),
                ('description', models.TextField()),
                ('stat1_number', models.CharField(default='500+', max_length=20)),
                ('stat1_text', models.CharField(default='Monthly Tons', max_length=50)),
                ('stat2_number', models.CharField(default='100%', max_length=20)),
                ('stat2_text', models.CharField(default='QC Passed', max_length=50)),
                ('stat3_number', models.CharField(default='50+', max_length=20)),
                ('stat3_text', models.CharField(default='Countries', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Building the Future of Global Manufacturing', max_length=200)),
                ('subtitle', models.TextField()),
                ('bg_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='about/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='A Legacy of Strength', max_length=200)),
                ('description', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='about/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to hide/show this section on the frontend.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of this section on the page (lower numbers appear first).')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='about/team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to hide/show this section on the frontend.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of this section on the page (lower numbers appear first).')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='about/testimonials/')),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutExcellenceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to hide/show this section on the frontend.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of this section on the page (lower numbers appear first).')),
                ('icon', models.CharField(default='shield-check', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('excellence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='about.aboutexcellence')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutStoryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to hide/show this section on the frontend.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of this section on the page (lower numbers appear first).')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='about.aboutstory')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
