# Generated by Django 5.2.6 on 2026-08-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutstory',
            name='title_highlight',
            field=models.CharField(default='Strength', help_text="The word that will be colored differently (e.g. 'Strength')", max_length=200),
        ),
        migrations.AddField(
            model_name='aboutstorypoint',
            name='icon',
            field=models.CharField(default='check-circle-2', help_text='Lucide icon name (e.g., check-circle-2)', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutstory',
            name='title',
            field=models.CharField(default='A Legacy of', help_text="The first part of the title (e.g. 'A Legacy of')", max_length=200),
        ),
    ]
