# Generated by Django 5.2.6 on 2026-08-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutstory_title_highlight_aboutstorypoint_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutexcellence',
            name='title_highlight',
            field=models.CharField(default='Excellence', help_text="The word that will be colored gold (e.g. 'Excellence')", max_length=200),
        ),
        migrations.AddField(
            model_name='aboutexcellence',
            name='title_suffix',
            field=models.CharField(blank=True, default='at Scale', help_text="The last part of the title (e.g. 'at Scale')", max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutexcellence',
            name='title',
            field=models.CharField(default='Engineering', help_text="The first part of the title (e.g. 'Engineering')", max_length=200),
        ),
    ]
