# Generated by Django 5.2.6 on 2026-08-05 18:04

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact Us', max_length=200)),
                ('subtitle', models.TextField(default='Get in touch with our team.')),
                ('bg_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='contact/')),
                ('address', models.TextField(default='123 Industrial Ave, Tianjin, China')),
                ('email', models.EmailField(default='info@tianjinfibernet.com', max_length=254)),
                ('phone', models.CharField(default='+86 123 4567 8900', max_length=50)),
                ('business_hours', models.TextField(default='Mon-Fri: 9:00 AM - 6:00 PM')),
                ('map_iframe', models.TextField(blank=True, help_text='Google Maps iframe embed code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
