# Generated by Django 5.2.6 on 2026-10-05 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingerEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.hostinger.com', max_length=200, verbose_name='Hostinger SMTP Host')),
                ('smtp_port', models.IntegerField(default=465, help_text='Default is 465 for SSL or 587 for TLS', verbose_name='SMTP Port')),
                ('smtp_user', models.CharField(blank=True, help_text='Your Hostinger email address, e.g. info@tjropenet.com', max_length=255, verbose_name='Hostinger Email (Username)')),
                ('smtp_password', models.CharField(blank=True, help_text='Your Hostinger email password', max_length=255, verbose_name='Hostinger Email Password')),
                ('use_ssl', models.BooleanField(default=True, verbose_name='Use SSL (Port 465)')),
                ('use_tls', models.BooleanField(default=False, verbose_name='Use TLS (Port 587)')),
                ('sender_name', models.CharField(blank=True, default='Tianbao Group', max_length=150, verbose_name='Default Sender Name')),
                ('default_signature', models.TextField(blank=True, default='Best Regards,\nTianbao Group\nhttps://tjropenet.com', verbose_name='Default Email Signature')),
                ('is_active', models.BooleanField(default=True, verbose_name='Enable Hostinger SMTP')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hostinger Email Setting',
                'verbose_name_plural': 'Hostinger Email Settings',
            },
        ),
        migrations.CreateModel(
            name='SentEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=255, verbose_name='Recipient Email(s)')),
                ('cc', models.CharField(blank=True, max_length=255, verbose_name='Cc')),
                ('bcc', models.CharField(blank=True, max_length=255, verbose_name='Bcc')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message Content')),
                ('attachment_name', models.CharField(blank=True, max_length=255, verbose_name='Attachment Name')),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Failed', 'Failed')], default='Sent', max_length=20, verbose_name='Delivery Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Details')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sent By')),
            ],
            options={
                'verbose_name': 'Sent Email Log',
                'verbose_name_plural': 'Sent Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
