# Generated by Django 5.2.6 on 2026-10-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0002_hostingeremailsettings_sentemaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Message ID')),
                ('uid', models.CharField(blank=True, max_length=100, verbose_name='IMAP UID')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='Sender Name')),
                ('sender_email', models.CharField(db_index=True, max_length=255, verbose_name='Sender Email')),
                ('recipient', models.CharField(blank=True, max_length=255, verbose_name='Recipient')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='Subject')),
                ('snippet', models.CharField(blank=True, max_length=300, verbose_name='Snippet Preview')),
                ('body_text', models.TextField(blank=True, verbose_name='Body (Plain Text)')),
                ('body_html', models.TextField(blank=True, verbose_name='Body (HTML)')),
                ('has_attachment', models.BooleanField(default=False, verbose_name='Has Attachment')),
                ('attachment_names', models.CharField(blank=True, max_length=500, verbose_name='Attachment Names')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('is_starred', models.BooleanField(default=False, verbose_name='Is Starred')),
                ('folder', models.CharField(default='INBOX', max_length=50, verbose_name='Folder')),
                ('received_at', models.DateTimeField(db_index=True, verbose_name='Received Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Synced At')),
            ],
            options={
                'verbose_name': 'Received Email',
                'verbose_name_plural': 'Received Emails (Inbox)',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='hostingeremailsettings',
            name='imap_host',
            field=models.CharField(default='imap.hostinger.com', max_length=200, verbose_name='Hostinger IMAP Host (Incoming)'),
        ),
        migrations.AddField(
            model_name='hostingeremailsettings',
            name='imap_port',
            field=models.IntegerField(default=993, help_text='Default is 993 for SSL', verbose_name='IMAP Port'),
        ),
        migrations.AddField(
            model_name='hostingeremailsettings',
            name='use_imap_ssl',
            field=models.BooleanField(default=True, verbose_name='Use IMAP SSL'),
        ),
    ]
