# Generated by Django 5.2.6 on 2026-08-05 18:04

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='navigation/')),
                ('about_text', models.TextField(blank=True, default='Brief description about the company for the footer.')),
                ('copyright_text', models.CharField(default='© 2026 Company Name. All Rights Reserved.', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='navigation/')),
                ('logo_alt', models.CharField(default='Site Logo', max_length=100)),
                ('cta_text', models.CharField(default='Get Quote', max_length=50)),
                ('cta_link', models.CharField(default='/contact/', max_length=200)),
            ],
            options={
                'verbose_name': 'Navbar Settings',
                'verbose_name_plural': 'Navbar Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to hide/show this section on the frontend.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of this section on the page (lower numbers appear first).')),
                ('platform', models.CharField(help_text='e.g., Facebook, Twitter, LinkedIn', max_length=50)),
                ('icon_class', models.CharField(help_text='FontAwesome icon class (e.g., fab fa-facebook)', max_length=50)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
