# Generated by Django 5.2.6 on 2026-08-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(blank=True, help_text='FontAwesome or Lucide icon name (e.g., facebook, twitter, linkedin)', max_length=50, null=True),
        ),
    ]
