# Generated by Django 5.2.6 on 2026-08-05 18:04

import ckeditor.fields
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Optimal length is 50-60 characters.', max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='Optimal length is 150-160 characters.', verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255, verbose_name='Meta Keywords')),
                ('canonical_url', models.URLField(blank=True, help_text='Leave blank to use the current page URL.', verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, help_text='Title for Facebook/LinkedIn sharing.', max_length=255, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='Description for Facebook/LinkedIn sharing.', verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, help_text='Image for Facebook/LinkedIn sharing (1200x630px recommended).', null=True, upload_to='seo/og/', verbose_name='OG Image')),
                ('robots_index', models.BooleanField(default=True, help_text='Allow search engines to index this page.', verbose_name='Index')),
                ('robots_follow', models.BooleanField(default=True, help_text='Allow search engines to follow links on this page.', verbose_name='Follow')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to hide/show this section on the frontend.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of this section on the page (lower numbers appear first).')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('hero_text', models.CharField(help_text='Text to display in the hero section for this category.', max_length=255)),
                ('hero_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='categories/')),
                ('hero_image_alt', models.CharField(default='Category Hero Image', help_text='Alt text for SEO.', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Optimal length is 50-60 characters.', max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='Optimal length is 150-160 characters.', verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255, verbose_name='Meta Keywords')),
                ('canonical_url', models.URLField(blank=True, help_text='Leave blank to use the current page URL.', verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, help_text='Title for Facebook/LinkedIn sharing.', max_length=255, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='Description for Facebook/LinkedIn sharing.', verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, help_text='Image for Facebook/LinkedIn sharing (1200x630px recommended).', null=True, upload_to='seo/og/', verbose_name='OG Image')),
                ('robots_index', models.BooleanField(default=True, help_text='Allow search engines to index this page.', verbose_name='Index')),
                ('robots_follow', models.BooleanField(default=True, help_text='Allow search engines to follow links on this page.', verbose_name='Follow')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to hide/show this section on the frontend.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of this section on the page (lower numbers appear first).')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('main_image', imagekit.models.fields.ProcessedImageField(upload_to='products/main/')),
                ('main_image_alt', models.CharField(default='Product Image', help_text='Alt text for SEO.', max_length=255)),
                ('features', models.TextField(blank=True, help_text='Enter each feature on a new line')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='products/additional/')),
                ('alt_text', models.CharField(default='Product Gallery Image', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
