# Generated by Django 5.2.6 on 2026-08-25 15:30

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='og_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image for Facebook/LinkedIn sharing (1200x630px recommended).', null=True, upload_to='seo/og/', verbose_name='OG Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='og_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image for Facebook/LinkedIn sharing (1200x630px recommended).', null=True, upload_to='seo/og/', verbose_name='OG Image'),
        ),
    ]
